name: MERN CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Backend setup
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Backend Linter
        working-directory: ./backend
        run: npm run lint --if-present

      - name: Run Backend Tests
        working-directory: ./backend
        env:
          MONGO_URI: mongodb://localhost:27017/testdb
          JWT_SECRET: testsecret
        run: npm test --if-present

      # Frontend setup
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Frontend Linter
        working-directory: ./frontend
        run: npm run lint --if-present

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test --if-present
